name: test_konsi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  go_router: ^14.2.1
  equatable: ^2.0.5
  sqflite: ^2.2.8+1
  path_provider: ^2.0.15
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  flutter_bloc: ^8.1.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  mockito: ^5.4.4
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
